spring:
  application:
    name: kafka_streams

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-streams-demo
    admin:
      auto-create: true
      properties:
        auto.create.topics.enable: true
    streams:
      application-id: kafka-streams
      properties:
        state.dir: C:/kafka-streams-state

logging:
  level:
    root: info

