spring:
  application:
    name: KafkaStreams

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-streams-demo
    admin:
      auto-create: true
      properties:
        auto.create.topics.enable: true
    streams:
      application-id: kafka-streams-demo-${random.uuid}
      state-dir: /tmp/kafka-streams/${spring.application.name}
      properties:
        default.topic.replication.factor: 1
        state.cleanup.delay.ms: 0
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

server:
  port: 8091


